"use client"; // Why: Error boundaries must be client components to catch React lifecycle errors.

import { useEffect } from "react";
import { AlertTriangle, RefreshCcw, Home } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // Why: Log the error to an external tracking service so the engineering team is alerted immediately.
    // The 'digest' is a hash of the error generated by Next.js for correlating server-side logs.
    console.error("[APPLICATION CRASH]:", error, "Digest:", error.digest);
  }, [error]);

  return (
    <div className="flex min-h-[60vh] w-full flex-col items-center justify-center rounded-lg p-8 text-center">
      <div className="flex h-20 w-20 items-center justify-center rounded-full bg-red-100 mb-6">
        <AlertTriangle className="h-10 w-10 text-red-600" aria-hidden="true" />
      </div>
      
      <h2 className="text-2xl font-semibold tracking-tight mb-2">
        System Error Encountered
      </h2>
      
      <p className="text-muted-foreground max-w-md mb-8">
        The application experienced an unexpected fault. Our engineering team has been notified. Please attempt to refresh the view.
      </p>
      
      <div className="flex gap-4">
        <Button 
          onClick={() => reset()} 
          variant="default"
          className="flex items-center gap-2"
        >
          <RefreshCcw className="h-4 w-4" />
          Attempt Recovery
        </Button>
        
        {/* Why: A hard escape hatch. If the localized state is deeply corrupted, a full page reload to a safe route is required. */}
        <Button 
          onClick={() => window.location.href = '/overview'} 
          variant="outline"
          className="flex items-center gap-2"
        >
          <Home className="h-4 w-4" />
          Return to Dashboard
        </Button>
      </div>
    </div>
  );
}